import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import OverviewMarketData from "./components/OverviewMarketData";
import Navbar from "./components/Navbar";

const inter = Inter({
  subsets: ["latin"],
});

const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space_grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${space_grotesk.className}`}>
        <ReduxProvider>
          <OverviewMarketData />
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
